# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Old Bob
description: >- # this means to ignore newlines until "baseurl:"
  Il vecchio Bob è seduto su un porticato. Si sentono solo i grilli, il cigolio della sedia e le plettrate sulla chitarra.
  Gli Old Bob sono una band di Roma che suona un mix di Power Blues, Stoner e Southern Rock cantato in Italiano.
baseurl:  # the subpath of your site, e.g. /blog
url: https://www.oldbobgunpowderband.it # the base hostname & protocol for your site, e.g. http://example.com
email: oldbobgunpowderband.info@gmail.com
facebook: https://www.facebook.com/oldbobband
tiktok: https://www.tiktok.com/@oldbob_band
instagram: https://www.instagram.com/oldbob_band/
youtube: https://www.youtube.com/channel/UC3ZiABarsYb2TvxmmZp6h4w
soundcloud: https://soundcloud.com/oldbobgunpowderband
bandcamp: https://oldbob.bandcamp.com/
spotify: https://open.spotify.com/intl-it/artist/0CuLLkHuuGhzGUvtHMVddy?si=5zX4pXFSRdOGgliyMP2whw

plugins:
  - jekyll-multiple-languages-plugin

languages: ["it", "en"]
# exclude_from_localizations: ["js", "sounds", "img", "fonts", "css", "doc"]
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
